src/app/(navbar)/community/page.tsx
src/app/api/board/route.ts
src/app/api/callback/route.ts
src/app/auth/callback/page.tsx
src/components/common/CategoryList.tsx
src/components/common/Icons.tsx
src/components/common/MultiPleCard.tsx
src/components/common/SearchInput.tsx
src/components/community/CommunityBoardList.tsx
src/components/detail/DetailInfo.tsx
src/components/layouts/Navbar.tsx
yarn.lock

--- code review ---
navbar update && fix
icon update && fix
postImte onclick update && fix

[hot fix] code review /w Mia , Mrkang

---

src/app/(navbar)/wishlist/page.tsx
src/components/common/CategoryList.tsx
src/components/common/RangeSlider.tsx
src/components/map/MapBottomSheet.tsx
src/components/map/filter/FilterModal.tsx

---- feature ----
added filter feature for map
range slider component(common)

[feat] Filter, Range slider

---

src/components/auth/signup/SignupFirst.tsx

--- fix error---
remove "checkPassword" in POST data

[fix] Fixsignup

---

src/app/api/(oauth)/signin/route.ts
src/app/signin/layout.tsx
src/app/signin/page.tsx
src/components/auth/signin/DefaultLogin.tsx
src/components/auth/signup/SignupFirst.tsx
src/components/common/Table.tsx
src/middleware.ts
src/recoil/authStates.ts

----new features---
setting middleware & login route with callbackUrl

[feat] middleware & login route

---

src/app/api/comment/[slug]/route.ts
src/app/api/comment/like/[slug]/route.ts
src/app/api/write/route.ts
src/app/auth/[...callback]/page.tsx
src/app/detail/[slug]/page.tsx
src/components/community/CommunityBoardList.tsx
src/components/detail/DetailComment.tsx
src/components/detail/DetailLikeBtn.tsx
src/components/detail/DetailMainProfile.tsx
src/components/detail/DetailNavbar.tsx
src/components/write/WriteHeader.tsx
src/hooks/usePosts.ts
src/service/board.ts
src/service/comment.ts
src/utils/utilFunc.ts

--------- fix feature --------
fixed detail like btn and wirte feature

[fix] wirte feature and detail page feature

---

src/app/api/map/detail/[postId]/route.ts
src/components/auth/signin/SocialAuth.tsx
src/service/map.ts

[fix] social login

---

src/components/auth/signin/SocialAuth.tsx

[fix] prefetch true to false

---

src/app/api/map/detail/[postId]/route.ts
src/components/auth/signin/SocialAuth.tsx
src/components/map/board/BoardList.tsx

[fix] social fixed

---

src/app/api/map/detail/[postId]/route.ts
src/components/auth/signin/SocialAuth.tsx
src/components/map/board/BoardList.tsx

Merge with Dev

---

src/app/api/map/category/route.ts
src/app/api/map/detail/[postId]/route.ts
src/app/api/map/geo/route.ts
src/app/globals.css
src/app/map/layout.tsx
src/components/BottomSheet.tsx
src/components/map/BottomSheetOption.tsx
src/components/map/CommunityMap.tsx
src/components/map/board/BoardList.tsx
src/components/map/filter/FilterOptions.tsx
src/components/map/header/MapHeader.tsx
src/components/map/marker/CustomOverlayMarker.tsx
src/components/write/WriteContent.tsx
src/components/write/location/ChooseLocation.tsx
src/components/write/location/SelectedLocation.tsx
src/components/write/tags/DisplayTags.tsx
src/hooks/useBottomSheet.ts
src/hooks/useDebounce.ts
src/hooks/useMapInstance.ts
src/hooks/useOutsideClick.ts
src/recoil/mapStates.ts
src/types/map.ts
src/types/response.ts
src/utils/constants/constants.ts

[fix] hot fix

---

src/app/api/(oauth)/callback/route.ts
src/app/api/(oauth)/signin/route.ts
src/app/api/(oauth)/signup/route.ts
src/app/api/comment/[slug]/route.ts
src/app/api/post/[slug]/route.ts
src/app/api/post/like/route.ts
src/app/api/profile/route.ts
src/app/api/user/route.ts
src/app/auth/[...callback]/page.tsx
src/app/editprofile/page.tsx
src/components/auth/signin/DefaultLogin.tsx
src/components/common/Button.tsx
src/components/detail/comment/DetailComment.tsx
src/components/detail/main/DetailButtons.tsx
src/components/detail/main/DetailMain.tsx
src/components/detail/main/LikeDetailCase.tsx
src/components/item/Table.tsx
src/components/profile/editpage/EditFirstModal.tsx
src/components/profile/editpage/EditProfileImage.tsx
src/components/profile/editpage/EditProfileInfo.tsx
src/middleware.ts
src/recoil/authStates.ts
src/service/comment.ts
src/service/token.ts
src/service/user.ts
src/utils/utilFunc.ts

[fix & feat] toast alert detailpage

[fix & feat] toast alert detailpage

---

src/components/bottomsheet/WriteSelect.tsx
src/components/home/search/SearchLocation.tsx
src/components/map/CommunityMap.tsx
src/components/write/WriteContent.tsx
src/components/write/WriteHeader.tsx
src/hooks/useMapCenter.ts

[hotfix] category

---

src/components/map/CommunityMap.tsx

[hotfix] fixed map

---

src/app/detail/[slug]/page.tsx
src/components/auth/signup/SignupSecond.tsx
src/components/detail/DetailHeader.tsx
src/components/detail/DetailModal.tsx
src/components/detail/DetailNavbar.tsx
src/components/detail/comment/DetailCommentItem.tsx
src/components/detail/comment/DetailReCommentItem.tsx
src/components/detail/comment/LikeCommentCase.tsx
src/components/detail/main/DetailButtons.tsx
src/components/detail/main/DetailMain.tsx
src/components/detail/main/LikeDetailCase.tsx
src/components/home/HomeLocationSeclect.tsx
src/components/home/search/DisplayRecents.tsx
src/components/profile/editpage/EditFirstModal.tsx
src/components/profile/mypage/MypageList.tsx
src/components/profile/mypage/MypageProfile.tsx
src/components/profile/mypage/MyscrapList.tsx
src/components/write/tags/DisplayTags.tsx
src/hooks/useDebounce.ts
src/recoil/mapStates.ts
src/service/clientCommet.ts
src/service/comment.ts

[hotfix] map error

---

src/components/map/CommunityMap.tsx
src/hooks/useMapInstance.ts

[fix[ hot fix

---

src/app/api/alert/[category]/route.ts
src/components/detail/comment/DetailComment.tsx
src/components/profile/editpage/EditProfileImage.tsx
src/components/write/WriteHeader.tsx
src/components/write/tags/DisplayTagItem.tsx

[hotfix] fix comment error

---

src/app/(nav)/mypage/[[...category]]/page.tsx
src/components/community/CommunityBoardList.tsx
src/components/community/CommunityLink.tsx
src/components/community/PostItem.tsx
src/components/detail/DetailNavbar.tsx
src/components/detail/comment/DetailComment.tsx
src/components/detail/comment/DetailCommentItem.tsx
src/components/detail/comment/DetailReCommentItem.tsx
src/recoil/commentState.ts
src/types/response.ts
src/utils/constants/board.ts

[fix] fixed comment response

---

src/app/(nav)/mypage/[[...category]]/page.tsx
src/components/common/Input.tsx
src/components/community/CommunityLink.tsx
src/components/home/location/LocationSelect.tsx
src/components/home/review/HomeReviewLists.tsx
src/components/home/search/SearchModal.tsx
src/components/layouts/Navbar.tsx
src/components/profile/mypage/MypageHeader.tsx
src/components/profile/mypage/MypageLink.tsx
src/components/profile/mypage/MypageList.tsx
src/recoil/homeState.ts

---------fix----------
fixed mypage error for fetch
fixed mypage rendering data
fixed serachModal focus

[fix]Home search modal && mypage

---

src/components/detail/DetailHeader.tsx
src/components/detail/main/DetailMainProfile.tsx
src/components/home/HomeLocationSeclect.tsx
src/components/home/search/SearchModal.tsx
src/components/item/UserProfile.tsx
src/components/profile/editpage/EditProfileImage.tsx

[hotfix] removede detialtime && profile img

---

src/components/auth/signup/SignupSecond.tsx

[hotfix] test homtown fix

---

src/components/home/HomeWeekleyTopFive.tsx
src/service/home.ts

- 이슈 번호를 적어주세요. 예) #123
- 어떤 변경사항이 있었는지 간략하게 설명해주세요.
- 리뷰어가 중점적으로 확인하면 좋을 부분을 알려주세요.
- 기타 참고할 사항이 있다면 적어주세요.

[fix] service logic 수정
